project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - qmd/data_management.qmd
    - qmd/analysis.qmd
    - qmd/redcap_formulas.qmd

website:
  title: "Cystatin C / Creatinine Ratio – Platinum AE"
  navbar:
    left:
      - href: index.qmd
        text: Summary
      - href: qmd/data_management.qmd
        text: Data Management
      - href: qmd/analysis.qmd
        text: Analysis
      - text: Side Requests
        menu:
          - href: qmd/redcap_formulas.qmd
            text: REDCap Formulas

format:
  html:
    theme: lumen
    toc: true
    toc-depth: 4
    code-fold: true

execute:
  eval: false
  warning: false
  message: false

knitr:
  opts_knit:
    root.dir: "/Users/to909/Desktop/Meg/Cystain C redcap"
