project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - data_management.qmd
    - analysis.qmd

website:
  title: "Cystatin C / Creatinine Ratio – Platinum AE"
  navbar:
    left:
      - href: index.qmd
        text: Summary
      - href: data_management.qmd
        text: Data Management
      - href: analysis.qmd
        text: Analysis

format:
  html:
    theme: lumen
    toc: true
    toc-depth: 4
    code-fold: true

execute:
  eval: false
  warning: false
  message: false
